stages:
  - build
  - deploy

variables:
  # Override the CI environment variable to false to allow warnings
  CI: "false"

build:
  stage: build
  image: node:latest
  script:
    - cd /builds/courses/csci-x691/dal-chess-club/dal-chess-club-x691  # Change to the project directory
    - npm install  # Install dependencies
    - npm run server & # Run the server in the background
    - npm run client & # Run the client in the background
    - sleep 10 # Wait for the server and client to start (adjust time if necessary)
    - npm run build  # Build your website
  artifacts:
    paths:
      - /builds/courses/csci-x691/dal-chess-club/dal-chess-club-x691/build/  # Make build directory available for deployment

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt-get update -qy && apt-get install -y lftp
    - lftp -c "set sftp:auto-confirm yes; open -u chessclub,eshooRi9oofaVah0 sftp://euro.cs.dal.ca; mirror -R /builds/courses/csci-x691/dal-chess-club/dal-chess-club-x691/build/ /local/websites/chessclub"
  only:
    - main  # Deploy only when changes are pushed to the main branch
